on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  build_server:
    name: Build server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        working-directory: server
        run: ./gradlew assembleDebug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: server/app/build/outputs/apk/debug/app-debug.apk
